### ISSUE TITLE
'MetaBlocks' object has no attribute 'append'

### ISSUE THREAD

**Issue by yunesj** [chdemko/pandoc-latex-unlisted#2]
I am getting an error when running pandoc-latex-unlisted.

Thanks!

```
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-latex-unlisted", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pandoc_latex_unlisted.py", line 43, in main
    return run_filter(header, prepare = prepare, doc = doc, finalize = finalize)
  File "/usr/local/lib/python2.7/site-packages/panflute/io.py", line 265, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/panflute/io.py", line 249, in run_filters
    finalize(doc)
  File "/usr/local/lib/python2.7/site-packages/pandoc_latex_unlisted.py", line 40, in finalize
    doc.metadata['header-includes'].append(MetaInlines(RawInline('\\let\\oldaddcontentsline\\addcontentsline', 'tex')))
AttributeError: 'MetaBlocks' object has no attribute 'append'
Error running filter pandoc-latex-unlisted:
```

**Comment by chdemko** [comment]
What version of pandoc are you running? And can you post an sample file and command line that does not work.
